import type { RETool, ToolId } from './types.js';

export const RE_TOOLS: RETool[] = [
  {
    id: 'ghidra',
    name: 'Ghidra',
    sub: 'NSA / Open source',
    color: '#8B5CF6',
    domains: ['malware', 'automotive', 'iot', 'network'],
    cfg: [
      { key: 'Heap Size', value: '-Xmx4G in ghidraRun', note: 'Increase for large binaries; 4–16 GB recommended' },
      { key: 'Decompiler Timeout', value: 'Edit > Tool Options > Decompiler > Timeout', note: 'Default 30 s; raise to 120 s for obfuscated code' },
      { key: 'Aggressive Analysis', value: 'Analysis > Auto Analyze > Aggressive Instruction Finder', note: 'Finds more code in stripped/packed binaries' },
      { key: 'Python 3 Scripting', value: 'PyGhidra / Ghidrathon bridge', note: 'Install Ghidrathon for full Python 3 support' },
      { key: 'FLIRT / FID Sigs', value: 'File > Import FID / Apply Function Signatures', note: 'Import IDA .sig or Ghidra .fidb to auto-name library functions' },
      { key: 'Architecture', value: 'Language selection at import time', note: 'Supports x86/x64, ARM, MIPS, PowerPC, RISC-V, and many more' },
      { key: 'Debugger / Emulate', value: 'Debugger tool window; in-process emulation via Sleigh', note: 'Connect remote GDB stub or use built-in emulator for shellcode' },
      { key: 'Project Sharing', value: 'Ghidra Server (ghidraSvr)', note: 'Multi-user repo; requires Java RMI; use SSH tunnel for remote access' },
    ],
    hk: [
      { keys: ['G'], action: 'Go to address', context: 'Listing / Decompiler' },
      { keys: ['L'], action: 'Rename symbol', context: 'Listing / Decompiler' },
      { keys: ['T'], action: 'Retype variable / symbol', context: 'Decompiler' },
      { keys: ['F'], action: 'Create function at cursor', context: 'Listing' },
      { keys: ['D'], action: 'Disassemble at cursor', context: 'Listing' },
      { keys: ['Ctrl', 'E'], action: 'Open decompiler for current function', context: 'Listing' },
      { keys: ['Ctrl', 'Shift', 'E'], action: 'Edit function signature', context: 'Decompiler' },
      { keys: ['X'], action: 'Show cross-references (xrefs)', context: 'Listing / Decompiler' },
      { keys: ['Ctrl', 'L'], action: 'Import function signatures (FID)', context: 'Global' },
      { keys: ['Ctrl', 'F'], action: 'Search program text / memory', context: 'Global' },
      { keys: ['Ctrl', 'G'], action: 'Go to file offset', context: 'Listing' },
      { keys: ['Alt', '←'], action: 'Navigate back', context: 'Global' },
      { keys: ['Space'], action: 'Toggle listing ↔ decompiler sync', context: 'Global' },
      { keys: ['Ctrl', 'Z'], action: 'Undo last action', context: 'Global' },
    ],
    ho: [
      { direction: 'to', tool: 'x64dbg', procedure: 'Export patched binary via File > Export Program; load in x64dbg for dynamic tracing', artifact: 'Patched PE / ELF binary' },
      { direction: 'to', tool: 'IDA Pro', procedure: 'Export Ghidra XML (File > Export Program > XML); import into IDA via idat loader', artifact: 'Ghidra XML export (.xml)' },
      { direction: 'from', tool: 'Wireshark', procedure: 'Import PCAP payload bytes; define data type in Ghidra to parse protocol structs', artifact: 'Raw protocol payload bytes' },
      { direction: 'from', tool: 'x64dbg', procedure: 'Export memory dump; load as raw binary in Ghidra with correct base address', artifact: 'Memory dump (.dmp / .bin)' },
      { direction: 'to', tool: 'SavvyCAN', procedure: 'Extract CAN message parser logic; port struct definitions to SavvyCAN DBC format', artifact: 'Struct definitions / DBC snippet' },
    ],
    pr: [
      { format: '.gpr / .rep', name: 'Ghidra Project', notes: 'Project folder; .rep is repository metadata; never edit manually' },
      { format: '.xml', name: 'Ghidra XML Export', notes: 'Portable program representation; use for IDA import or backup' },
      { format: '.fidb', name: 'Function ID Database', notes: 'Library signature database; import to auto-name known functions' },
      { format: '.ldefs / .slaspec', name: 'Sleigh Language Definition', notes: 'Processor spec files; edit to add custom architectures or co-processors' },
      { format: '.java / .py', name: 'Ghidra Script', notes: 'Scripts in Java or Python (via Ghidrathon); run from Script Manager' },
    ],
  },
  {
    id: 'ida',
    name: 'IDA Pro',
    sub: 'Hex-Rays',
    color: '#EC4899',
    domains: ['malware', 'automotive', 'iot', 'network'],
    cfg: [
      { key: 'Decompiler (Hex-Rays)', value: 'View > Open Subviews > Pseudocode (F5)', note: 'Requires separate Hex-Rays decompiler license per architecture' },
      { key: 'FLIRT Signatures', value: 'File > Load File > FLIRT Signature File', note: 'Apply .sig files to auto-name statically-linked library functions' },
      { key: 'Type Libraries', value: 'View > Type Libraries (Shift+F11)', note: 'Load .til files for Windows API, POSIX, custom structs' },
      { key: 'IDA Python', value: 'Built-in Python 3; pip install via idapyswitch', note: 'Full scripting API; community scripts at github.com/EiNSTeiN-' },
      { key: 'Remote Debugging', value: 'Debugger > Select Debugger > Remote GDB / Win32 Remote', note: 'Deploy ida_server / win32_server on target; connect over SSH tunnel' },
      { key: 'Processor Module', value: 'Selected at load time; change via Edit > Processor Options', note: 'Custom .py processor modules for proprietary ISAs' },
      { key: 'Database (.idb/.i64)', value: 'Auto-saved IDA database; includes all analysis, names, comments', note: 'Back up regularly; .i64 for 64-bit, .idb for 32-bit' },
      { key: 'Lumina Server', value: 'Options > Connect to Lumina', note: 'Crowd-sourced function name sharing; requires Hex-Rays account' },
    ],
    hk: [
      { keys: ['F5'], action: 'Open Hex-Rays decompiler (pseudocode)', context: 'Disassembly view' },
      { keys: ['N'], action: 'Rename item at cursor', context: 'Disassembly / Pseudocode' },
      { keys: ['Y'], action: 'Change type of item', context: 'Disassembly / Pseudocode' },
      { keys: ['P'], action: 'Create function at cursor', context: 'Disassembly' },
      { keys: ['C'], action: 'Convert to code', context: 'Disassembly' },
      { keys: ['X'], action: 'Cross-references to cursor', context: 'Disassembly / Pseudocode' },
      { keys: ['G'], action: 'Go to address', context: 'Global' },
      { keys: ['Ctrl', 'F'], action: 'Search text', context: 'Global' },
      { keys: ['Alt', '←'], action: 'Navigate back', context: 'Global' },
      { keys: ['Ctrl', 'Z'], action: 'Undo', context: 'Global' },
      { keys: ['Shift', 'F12'], action: 'Open Strings window', context: 'Global' },
      { keys: ['Ctrl', 'S'], action: 'Save database', context: 'Global' },
      { keys: ['Tab'], action: 'Switch disassembly ↔ pseudocode', context: 'Decompiler' },
      { keys: ['Spacebar'], action: 'Toggle graph / text view', context: 'Disassembly' },
    ],
    ho: [
      { direction: 'to', tool: 'x64dbg', procedure: 'Note function addresses; set breakpoints in x64dbg matching IDA offsets (rebase if ASLR)', artifact: 'Function address list / IDA idb' },
      { direction: 'to', tool: 'Ghidra', procedure: 'Export IDA .idb via idat -c; use Ghidra XML loader or community IDA2Ghidra plugin', artifact: 'IDA database / XML export' },
      { direction: 'from', tool: 'Wireshark', procedure: 'Extract protocol payload; define C struct in IDA using Edit > Structs to parse captured data', artifact: 'Captured protocol payload' },
      { direction: 'from', tool: 'x64dbg', procedure: 'Export memory snapshot; reload in IDA as additional segment at correct base', artifact: 'x64dbg memory dump' },
    ],
    pr: [
      { format: '.idb / .i64', name: 'IDA Database', notes: 'Primary analysis file; .idb=32-bit, .i64=64-bit; contains all annotations' },
      { format: '.sig', name: 'FLIRT Signature', notes: 'Library function signature; generated with sigmake; apply to identify standard library code' },
      { format: '.til', name: 'Type Information Library', notes: 'Struct/enum/typedef library; load via Shift+F11 to get Windows/POSIX types' },
      { format: '.py / .idc', name: 'IDA Script', notes: 'Python (.py) or IDC (.idc) automation scripts; run via File > Script File' },
      { format: '.pat', name: 'FLIRT Pattern File', notes: 'Intermediate format; processed by sigmake to produce .sig files' },
    ],
  },
  {
    id: 'dnspy',
    name: 'dnSpy Ex',
    sub: '.NET / Managed',
    color: '#6366F1',
    domains: ['malware', 'iot'],
    cfg: [
      { key: 'Decompiler Engine', value: 'Edit > Options > Decompiler (ILSpy / Roslyn)', note: 'Switch between ILSpy and Roslyn decompiler backends' },
      { key: 'Assembly List', value: 'Edit > Open Assembly List', note: 'Manage sets of .NET assemblies; use separate lists per project' },
      { key: 'Debug .NET Process', value: 'Debug > Start Debugging (or Attach)', note: 'Full managed debugger; step through decompiled C# directly' },
      { key: 'Edit & Continue', value: 'Right-click method > Edit Method Body', note: 'Modify IL on the fly; save with Ctrl+Shift+S' },
      { key: 'Module Writes', value: 'File > Save Module', note: 'Persist patches back to the assembly DLL/EXE' },
      { key: 'Analyzer', value: 'View > Analyzer (Ctrl+Shift+R)', note: 'Find all references, overrides, instantiations of a type/method' },
      { key: 'Themes', value: 'Edit > Options > UI > Theme', note: 'Dark mode recommended for long analysis sessions' },
      { key: 'Plugin Support', value: 'Extensions directory in dnSpy folder', note: 'Community plugins for deobfuscation, string decryption, etc.' },
    ],
    hk: [
      { keys: ['F5'], action: 'Start / continue debugging', context: 'Debugger' },
      { keys: ['F9'], action: 'Toggle breakpoint', context: 'Decompiler / IL' },
      { keys: ['F10'], action: 'Step over', context: 'Debugger' },
      { keys: ['F11'], action: 'Step into', context: 'Debugger' },
      { keys: ['Ctrl', 'Shift', 'R'], action: 'Open Analyzer panel', context: 'Global' },
      { keys: ['Ctrl', 'F'], action: 'Search in assemblies', context: 'Global' },
      { keys: ['Ctrl', 'Shift', 'S'], action: 'Save all modified modules', context: 'Global' },
      { keys: ['Ctrl', 'G'], action: 'Go to token / offset', context: 'Decompiler' },
      { keys: ['Alt', '←'], action: 'Navigate back', context: 'Global' },
      { keys: ['Ctrl', 'D'], action: 'Decompile selected method', context: 'Assembly tree' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'Save compiled native DLL; load in Ghidra for native interop analysis', artifact: 'Native interop DLL' },
      { direction: 'to', tool: 'Wireshark', procedure: 'Identify C2 serialization format in decompiled code; correlate with Wireshark captures', artifact: 'Serialization format notes' },
      { direction: 'from', tool: 'x64dbg', procedure: 'Dump mixed-mode assembly from x64dbg; import managed sections into dnSpy', artifact: 'Mixed-mode assembly dump' },
    ],
    pr: [
      { format: '.dll / .exe', name: '.NET Assembly', notes: 'Primary input; both managed and mixed-mode assemblies supported' },
      { format: '.pdb', name: 'Program Database', notes: 'Debug symbols; load alongside assembly for full source mapping' },
      { format: '.xml', name: 'XML Documentation', notes: 'IntelliSense doc file; loaded automatically if present alongside assembly' },
      { format: '.nupkg', name: 'NuGet Package', notes: 'Extract and load contained DLLs for library analysis' },
    ],
  },
  {
    id: 'x64dbg',
    name: 'x64dbg',
    sub: 'Windows debugger',
    color: '#14B8A6',
    domains: ['malware', 'automotive', 'iot', 'network'],
    cfg: [
      { key: 'Symbol Store', value: 'Options > Preferences > Engine > Symbol store path', note: 'Point to local symsrv cache; set _NT_SYMBOL_PATH for PDB resolution' },
      { key: 'Plugin Directory', value: '<x64dbg>/x32/ or /x64/ plugins folder', note: 'ScyllaHide, xAnalyzer, SwissArmyKnife are essential community plugins' },
      { key: 'ScyllaHide', value: 'Plugin > ScyllaHide > InjectionMethod', note: 'Anti-anti-debug; bypass IsDebuggerPresent, NtQueryInformationProcess, etc.' },
      { key: 'Breakpoint Logging', value: 'Right-click breakpoint > Edit > Log condition', note: 'Use {arg1}, {eax} etc. for conditional logging without pausing' },
      { key: 'Memory Map', value: 'View > Memory Map (Alt+M)', note: 'Monitor heap, stack, mapped files; right-click to dump region' },
      { key: 'Trace Recording', value: 'Debug > Trace into / Trace over', note: 'Record full execution trace; analyze later with run-trace viewer' },
      { key: 'Script Engine', value: 'File > Run Script; built-in x64dbg script language + Python via x64dbgpy', note: 'Automate tasks; Python bridge allows Unicorn/Capstone integration' },
      { key: 'ASLR Rebasing', value: 'Module base shown in Modules panel; compute offset = VA − imagebase', note: 'Use rebase command or set preferred imagebase to match static analysis' },
    ],
    hk: [
      { keys: ['F2'], action: 'Toggle software breakpoint', context: 'Disassembly' },
      { keys: ['F7'], action: 'Step into', context: 'Debugger' },
      { keys: ['F8'], action: 'Step over', context: 'Debugger' },
      { keys: ['F9'], action: 'Run (continue execution)', context: 'Debugger' },
      { keys: ['Ctrl', 'F2'], action: 'Restart process', context: 'Debugger' },
      { keys: ['F4'], action: 'Run to cursor', context: 'Disassembly' },
      { keys: ['Alt', 'M'], action: 'Open Memory Map', context: 'Global' },
      { keys: ['Ctrl', 'G'], action: 'Go to expression / address', context: 'Disassembly / Dump' },
      { keys: ['Ctrl', 'B'], action: 'Open Breakpoints panel', context: 'Global' },
      { keys: [';'], action: 'Add comment at cursor', context: 'Disassembly' },
      { keys: [':'], action: 'Assemble instruction at cursor', context: 'Disassembly' },
      { keys: ['Ctrl', 'P'], action: 'Patch file (apply memory patches to disk)', context: 'Global' },
      { keys: ['Alt', 'K'], action: 'Open Call Stack', context: 'Global' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'Dump process memory at runtime; load dump in Ghidra as additional binary to correlate dynamic behavior', artifact: 'Process memory dump (.dmp)' },
      { direction: 'to', tool: 'IDA Pro', procedure: 'Export renamed labels via x64dbg script; import into IDA to enrich static analysis', artifact: 'Label / comment export' },
      { direction: 'from', tool: 'Ghidra', procedure: 'Bring over function addresses and names from Ghidra analysis; apply as x64dbg labels', artifact: 'Address / symbol list' },
      { direction: 'from', tool: 'Wireshark', procedure: 'Identify network functions to breakpoint based on Wireshark traffic patterns', artifact: 'Target function addresses' },
    ],
    pr: [
      { format: '.dd32 / .dd64', name: 'x64dbg Database', notes: 'Per-binary analysis DB; stores labels, comments, breakpoints' },
      { format: '.dmp', name: 'Minidump / Full Dump', notes: 'Windows crash or manual dump; load in WinDbg or Ghidra for offline analysis' },
      { format: '.x64dbg.json', name: 'Script / Session JSON', notes: 'Serialized breakpoint/patch session; share across team for reproducible analysis' },
      { format: '.py / .txt', name: 'x64dbg Script', notes: 'Automation scripts; .py for Python bridge, .txt for native script language' },
    ],
  },
  {
    id: 'ws',
    name: 'Wireshark',
    sub: 'Packet analysis',
    color: '#F97316',
    domains: ['malware', 'automotive', 'iot', 'network'],
    cfg: [
      { key: 'Capture Interface', value: 'Capture > Options > Interface', note: 'Select specific NIC; use promiscuous mode for all traffic; use monitor mode for 802.11' },
      { key: 'Display Filter', value: 'Filter bar at top of packet list', note: 'e.g. ip.addr==192.168.1.1 && tcp.port==443; saved filters reusable via bookmarks' },
      { key: 'TLS Decryption', value: 'Edit > Preferences > Protocols > TLS > (Pre)-Master-Secret log', note: 'Set SSLKEYLOGFILE env var in browser/app; point Wireshark to the log file' },
      { key: 'Custom Dissector', value: 'Edit > Preferences > Protocols; Lua script in plugins folder', note: 'Write Lua dissectors for proprietary protocols; place in personal plugins dir' },
      { key: 'Coloring Rules', value: 'View > Coloring Rules', note: 'Highlight C2, DNS tunneling, or anomalous packets for rapid triage' },
      { key: 'Statistics / IO Graph', value: 'Statistics > IO Graph; Statistics > Protocol Hierarchy', note: 'Identify bandwidth anomalies, protocol distribution, beaconing intervals' },
      { key: 'Follow Stream', value: 'Right-click > Follow > TCP/UDP/TLS Stream', note: 'Reconstruct full conversation; export raw bytes for further analysis' },
      { key: 'Remote Capture (rpcapd)', value: 'Capture > Options > Remote interface', note: 'Capture on remote host via rpcapd daemon; useful for embedded targets' },
    ],
    hk: [
      { keys: ['Ctrl', 'E'], action: 'Start / stop capture', context: 'Global' },
      { keys: ['Ctrl', 'K'], action: 'Open Capture Options', context: 'Global' },
      { keys: ['Ctrl', 'F'], action: 'Find packet', context: 'Global' },
      { keys: ['Ctrl', 'G'], action: 'Go to packet by number', context: 'Packet list' },
      { keys: ['Ctrl', 'M'], action: 'Mark / unmark packet', context: 'Packet list' },
      { keys: ['Ctrl', 'Shift', 'N'], action: 'Next marked packet', context: 'Packet list' },
      { keys: ['Ctrl', 'R'], action: 'Show packet in new window', context: 'Packet list' },
      { keys: ['Alt', '→'], action: 'Navigate forward in history', context: 'Global' },
      { keys: ['Ctrl', 'Alt', 'F'], action: 'Apply as column', context: 'Packet details' },
      { keys: ['Ctrl', 'D'], action: 'Export Selected Packet Bytes', context: 'Packet list' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'Export raw payload bytes (File > Export Specified Packets > C Arrays); import into Ghidra as data block', artifact: 'Raw payload bytes / C array' },
      { direction: 'to', tool: 'IDA Pro', procedure: 'Export reassembled TCP stream; define protocol structs in IDA to parse binary data', artifact: 'Reassembled stream bytes' },
      { direction: 'to', tool: 'CANalyzer/SavvyCAN', procedure: 'Export CAN-over-IP frames to CSV; import into SavvyCAN for DBC-based decoding', artifact: 'CAN-over-IP PCAP / CSV' },
      { direction: 'from', tool: 'x64dbg', procedure: 'Trigger specific code paths in x64dbg while capturing; correlate execution events with packets', artifact: 'Timed execution trace' },
    ],
    pr: [
      { format: '.pcap / .pcapng', name: 'Packet Capture', notes: '.pcapng preferred (supports metadata, multiple interfaces); .pcap for legacy tool compat' },
      { format: '.lua', name: 'Wireshark Lua Dissector', notes: 'Custom protocol parser; place in personal plugins folder; auto-loaded at startup' },
      { format: '.json', name: 'Tshark JSON Export', notes: 'Machine-readable packet data via tshark -T json; useful for scripted analysis pipelines' },
      { format: '.csv', name: 'CSV Export', notes: 'File > Export Packet Dissections > CSV; for spreadsheet analysis of metadata' },
    ],
  },
  {
    id: 'can',
    name: 'CANalyzer / SavvyCAN',
    sub: 'CAN bus analysis',
    color: '#CA8A04',
    domains: ['automotive'],
    cfg: [
      { key: 'Hardware Interface', value: 'Vector CANalyzer: Tools > Options > Hardware; SavvyCAN: Connection > Connect to Device', note: 'Supports Vector VN-series, PEAK, Kvaser, SocketCAN adapters' },
      { key: 'DBC File', value: 'CANalyzer: Database > Add; SavvyCAN: DBC Manager > Load DBC', note: 'DBC defines message IDs and signal encoding; required for decoded view' },
      { key: 'Baud Rate', value: 'Set to match target vehicle network (typically 250 kbps or 500 kbps)', note: 'OBD-II port: 500 kbps; body network: 125–250 kbps; check with oscilloscope if unknown' },
      { key: 'Logging', value: 'CANalyzer: Measurement > Logging Configuration; SavvyCAN: File > Save Capture', note: 'Log to .asc (CANalyzer) or .csv (SavvyCAN); include timestamps for replay' },
      { key: 'Filters', value: 'Set ID-based pass/block filters to reduce noise on busy networks', note: 'ISO-TP (15765-2) multi-frame messages span multiple IDs; filter carefully' },
      { key: 'UDS / OBD-II', value: 'Use ISO-TP plugin in SavvyCAN; CANalyzer CAPL scripting for UDS sessions', note: 'Diagnostic services: 0x22 ReadDataByIdentifier, 0x2E WriteDataByIdentifier, 0x31 RoutineControl' },
      { key: 'CAPL Scripting', value: 'CANalyzer: Program panel; CAPL browser for .can scripts', note: 'CAPL is C-like; automate message injection, fuzz testing, UDS sessions' },
      { key: 'Signal Extraction', value: 'SavvyCAN: Analysis > Fuzzy Scope; bit-level signal finder for unknown DBCs', note: 'Use graphing to identify signals by correlation with vehicle actions (steering, throttle)' },
    ],
    hk: [
      { keys: ['F9'], action: 'Start / stop measurement', context: 'CANalyzer global' },
      { keys: ['F8'], action: 'Clear trace window', context: 'CANalyzer trace' },
      { keys: ['Ctrl', 'S'], action: 'Save current configuration / capture', context: 'Global' },
      { keys: ['Ctrl', 'L'], action: 'Open logging configuration', context: 'CANalyzer' },
      { keys: ['Ctrl', 'F'], action: 'Find message / signal', context: 'SavvyCAN' },
      { keys: ['Ctrl', 'D'], action: 'Toggle DBC decode on/off', context: 'SavvyCAN' },
      { keys: ['Ctrl', 'G'], action: 'Open graphing window', context: 'SavvyCAN' },
      { keys: ['Ctrl', 'R'], action: 'Start capture replay', context: 'SavvyCAN' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'Identify ECU firmware update messages; extract firmware payload bytes for Ghidra analysis', artifact: 'Firmware payload bytes' },
      { direction: 'from', tool: 'Wireshark', procedure: 'Import CAN-over-IP traffic exported from Wireshark; decode with local DBC', artifact: 'CAN-over-IP CSV / PCAP' },
      { direction: 'to', tool: 'Serial Port Monitor', procedure: 'Cross-reference CAN bus events with simultaneous serial diagnostic output', artifact: 'Synchronized CAN + serial log' },
    ],
    pr: [
      { format: '.dbc', name: 'DBC Database', notes: 'CAN signal/message definition; open standard; edit with CANdb++ or free DBC editors' },
      { format: '.asc', name: 'CANalyzer ASCII Log', notes: 'Human-readable timestamped CAN log; compatible with most CAN tools for replay' },
      { format: '.blf', name: 'Binary Logging Format', notes: 'Vector proprietary compressed log; high-performance capture; replay with CANalyzer' },
      { format: '.csv', name: 'SavvyCAN CSV Export', notes: 'Comma-separated frame log; timestamp, ID, DLC, data bytes; for scripted post-processing' },
    ],
  },
  {
    id: 'spm',
    name: 'Serial Port Monitor',
    sub: 'UART / COM analysis',
    color: '#3B82F6',
    domains: ['automotive', 'iot'],
    cfg: [
      { key: 'Port Selection', value: 'Session > New Session > Port (COMx / /dev/ttyUSBx)', note: 'Use Device Manager / dmesg to identify port; virtual COM ports via USB-serial adapters' },
      { key: 'Baud Rate', value: 'Match target device: 9600, 115200, 921600 common; use oscilloscope if unknown', note: 'Wrong baud rate produces garbled data (framing errors)' },
      { key: 'Data Bits / Parity / Stop', value: 'Typically 8N1 (8 data, no parity, 1 stop); adjust per device spec', note: 'RS-232 vs TTL voltage levels differ; use appropriate adapter / level shifter' },
      { key: 'Flow Control', value: 'Usually None for debug UARTs; RTS/CTS for high-speed data links', note: 'Software XON/XOFF flow control may appear in older embedded systems' },
      { key: 'Logging', value: 'Session > Log to File; capture raw bytes + decoded text', note: 'Log timestamped raw hex alongside ASCII for protocol analysis' },
      { key: 'Filters', value: 'View > Filters; highlight or hide specific byte sequences', note: 'Useful for filtering heartbeat / keep-alive messages to find meaningful data' },
      { key: 'Send Data', value: 'Session > Send Data; support for hex and ASCII; script via Python pyserial', note: 'Test command-response protocol; inject commands to enumerate debug features' },
      { key: 'Terminal Mode', value: 'Enable for interactive device consoles (U-Boot, Linux shell, AT commands)', note: 'VT100/ANSI emulation; configure line ending (LF vs CRLF) to match device' },
    ],
    hk: [
      { keys: ['Ctrl', 'N'], action: 'New monitoring session', context: 'Global' },
      { keys: ['Ctrl', 'S'], action: 'Save session / log', context: 'Global' },
      { keys: ['Ctrl', 'C'], action: 'Copy selected data', context: 'Data view' },
      { keys: ['Ctrl', 'F'], action: 'Find in captured data', context: 'Data view' },
      { keys: ['F5'], action: 'Refresh / re-open port', context: 'Global' },
      { keys: ['Ctrl', 'L'], action: 'Clear display buffer', context: 'Data view' },
      { keys: ['Ctrl', 'T'], action: 'Toggle terminal mode', context: 'Global' },
      { keys: ['Ctrl', 'H'], action: 'Toggle hex / ASCII view', context: 'Data view' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'Capture firmware update stream over serial; extract binary payload for Ghidra disassembly', artifact: 'Firmware binary extracted from serial' },
      { direction: 'to', tool: 'CANalyzer/SavvyCAN', procedure: 'Identify CAN gateway diagnostic commands sent over serial; correlate with CAN bus messages', artifact: 'Diagnostic command list' },
      { direction: 'from', tool: 'Ghidra', procedure: 'Use Ghidra-identified command opcodes to craft serial injection payloads', artifact: 'Command opcode list' },
    ],
    pr: [
      { format: '.log / .txt', name: 'Serial Log', notes: 'Timestamped hex + ASCII log; import into Wireshark via text2pcap for protocol analysis' },
      { format: '.pcap', name: 'Serial-to-PCAP', notes: 'Convert serial log with text2pcap -D; enables Wireshark dissector use on serial data' },
      { format: '.py', name: 'pyserial Script', notes: 'Python automation for send/receive sequences; use for automated fuzzing or enumeration' },
      { format: '.csv', name: 'Timestamped CSV', notes: 'Export for timing analysis; correlate serial events with CAN or network captures' },
    ],
  },
  {
    id: 'r2',
    name: 'Radare2 / Cutter',
    sub: 'Open-source RE framework',
    color: '#22D3EE',
    domains: ['malware', 'iot', 'firmware'],
    cfg: [
      { key: 'Config file', value: '~/.radare2rc', note: 'Persistent settings; e.color=true, e.asm.syntax=intel' },
      { key: 'Arch / bits', value: 'r2 -a arm -b 32 firmware.bin', note: 'Override auto-detection; also e asm.arch and e asm.bits at runtime' },
      { key: 'Analysis level', value: 'aaa (full) / aa (fast) / aaaa (paranoid)', note: 'Start with aa; add afl to list found functions then refine' },
      { key: 'Write mode', value: 'r2 -w binary (or oo+ at prompt)', note: 'Required for patching; use wox for hex overwrites' },
      { key: 'Scripting', value: 'r2pipe (Python/Node/Go) or #!python via shebang', note: 'pip install r2pipe; r2.cmdj() returns parsed JSON' },
      { key: 'Cutter GUI', value: 'cutter binary — Qt-based GUI wrapping r2', note: 'Decompiler via rz-ghidra plugin; install with rzpkg install rz-ghidra' },
      { key: 'ESIL emulation', value: 'aei; aeim; aepc 0x1000; aes (step)', note: 'Intermediate language emulator; useful for obfuscated shellcode' },
      { key: 'Projects', value: 'Ps project.r2 / Po project.r2', note: 'Saves flags, comments, analysis; portable across sessions' },
    ],
    hk: [
      { keys: ['?'], action: 'Help for current command group', context: 'Shell' },
      { keys: ['s', '0x401000'], action: 'Seek to address', context: 'Shell' },
      { keys: ['pd', '20'], action: 'Print disassembly (20 instructions)', context: 'Shell' },
      { keys: ['pdf'], action: 'Disassemble current function', context: 'Shell' },
      { keys: ['afn', 'newname'], action: 'Rename current function', context: 'Shell' },
      { keys: ['axt', '@', 'addr'], action: 'Cross-references to address', context: 'Shell' },
      { keys: ['iz'], action: 'List strings in data section', context: 'Shell' },
      { keys: ['iE'], action: 'List exports', context: 'Shell' },
      { keys: ['db', '0x401000'], action: 'Set breakpoint (debug mode)', context: 'Debug' },
      { keys: ['dc'], action: 'Continue execution', context: 'Debug' },
      { keys: ['V'], action: 'Visual mode (hex + disasm panels)', context: 'Shell' },
      { keys: ['VV'], action: 'Graph view of current function', context: 'Shell' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'r2 -qc "r2ghidra; echo" bin → outputs decompiled C. Or export JSON via r2 -qj bin and import into Ghidra via script.', artifact: 'r2ghidra decompiled output' },
      { direction: 'to', tool: 'x64dbg', procedure: 'Export flags: r2 -qc "aflj" bin | python3 r2_to_x64dbg.py > labels.json — import via Debug > Import Labels.', artifact: 'JSON label file' },
      { direction: 'from', tool: 'Binwalk', procedure: 'binwalk -e firmware.bin → extracted files → r2 each binary for per-component analysis.', artifact: 'extracted component binaries' },
      { direction: 'to', tool: 'Frida', procedure: 'r2 identifies function offsets → Frida hooks at base+offset for runtime validation.', artifact: 'function offsets' },
    ],
    pr: [
      { format: '.r2', name: 'Radare2 script', notes: 'Plain text r2 commands; run with r2 -i script.r2 binary' },
      { format: '.rdb', name: 'Radare2 project', notes: 'Saved session with flags, comments, analysis; Ps/Po commands' },
      { format: 'ESIL', name: 'ESIL bytecode', notes: 'Evaluable Strings Intermediate Language; stack-based, used for emulation' },
      { format: '.json', name: 'r2 JSON output', notes: 'All major commands support -j flag; pipe to jq for filtering' },
    ],
  },
  {
    id: 'frida',
    name: 'Frida',
    sub: 'Dynamic instrumentation',
    color: '#A78BFA',
    domains: ['malware', 'mobile', 'iot'],
    cfg: [
      { key: 'Install', value: 'pip install frida-tools frida', note: 'Also install frida-server on target device (match versions exactly)' },
      { key: 'Android setup', value: 'adb push frida-server /data/local/tmp/\nadb shell chmod 755 /data/local/tmp/frida-server\nadb shell /data/local/tmp/frida-server &', note: 'Root required; use Magisk Frida module for persistent install' },
      { key: 'iOS setup', value: 'Install via Cydia (jailbroken) or Frida gadget injection for unjailbroken', note: 'Gadget: inject frida-gadget.dylib and add frida-ios-dump for IPA extraction' },
      { key: 'Process attach', value: 'frida -U -n "com.example.app" (USB)\nfrida -H 192.168.1.1 -n app (remote)', note: '-f to spawn fresh; -p PID to attach by PID' },
      { key: 'Script reload', value: 'frida -l script.js --no-pause', note: 'Use frida --runtime=v8 for full ES2020 support' },
      { key: 'Stalker (tracing)', value: 'Stalker.follow(threadId, { events: {call:true,ret:true}, onReceive: cb })', note: 'High-overhead; use on short code paths only; instrument with transform for instruction-level' },
      { key: 'SSL pinning bypass', value: 'frida -U -l ssl-pinning-bypass.js -f com.example.app', note: 'Common scripts: frida-codeshare.com/pcipolloni/universal-android-ssl-pinning-bypass-with-frida' },
      { key: 'Objection', value: 'objection -g com.example.app explore', note: 'Frida wrapper: memory search, class/method listing, root bypass, file system browsing' },
    ],
    hk: [
      { keys: ['Interceptor.attach'], action: 'Hook function entry/exit', context: 'JS API' },
      { keys: ['Interceptor.replace'], action: 'Replace function entirely', context: 'JS API' },
      { keys: ['Memory.readByteArray'], action: 'Read raw bytes from address', context: 'JS API' },
      { keys: ['Memory.writeByteArray'], action: 'Patch bytes at address', context: 'JS API' },
      { keys: ['Java.use'], action: 'Get Java class reference (Android)', context: 'Java API' },
      { keys: ['Java.perform'], action: 'Run code on main Java thread', context: 'Java API' },
      { keys: ['ObjC.classes'], action: 'List all Objective-C classes (iOS)', context: 'ObjC API' },
      { keys: ['Process.enumerateModules'], action: 'List loaded modules / libraries', context: 'JS API' },
      { keys: ['Module.findExportByName'], action: 'Resolve exported symbol address', context: 'JS API' },
      { keys: ['frida-ps', '-U'], action: 'List USB-connected device processes', context: 'CLI' },
      { keys: ['frida-trace', '-U', '-i', '"recv*"'], action: 'Auto-trace matching exports', context: 'CLI' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'Frida logs runtime addresses → map back to Ghidra via base address: Ghidra_offset = runtime_addr - Module.getBaseAddress("lib.so").', artifact: 'runtime → static address mapping' },
      { direction: 'to', tool: 'Wireshark', procedure: 'Hook SSL_write/SSL_read → log plaintext to file or forward to SSLKEYLOGFILE equivalent for Wireshark TLS decryption.', artifact: 'plaintext session keys / decrypted buffer' },
      { direction: 'from', tool: 'JADX', procedure: 'JADX identifies Java class/method names → Frida Java.use("com.example.ClassName").methodName.implementation = function() {}', artifact: 'class and method names from JADX' },
      { direction: 'to', tool: 'Radare2', procedure: 'r2 static analysis provides function offsets → Frida hooks at Module.getBaseAddress() + offset for runtime validation.', artifact: 'function offset from r2 analysis' },
    ],
    pr: [
      { format: '.js', name: 'Frida script', notes: 'ES2020 JS; run with frida -l script.js; use rpc.exports for two-way communication' },
      { format: 'frida-codeshare', name: 'Community scripts', notes: 'frida.re/docs/codeshare — SSL bypass, root detection bypass, anti-debug bypass' },
      { format: 'RPC', name: 'Frida RPC', notes: 'rpc.exports = { fn: () => {} } in script; call from Python via script.exports.fn()' },
      { format: 'Gadget', name: 'Frida Gadget', notes: 'Inject into IPA/APK without device root; configure via frida-gadget-config.json' },
    ],
  },
  {
    id: 'jadx',
    name: 'JADX',
    sub: 'Android / APK decompiler',
    color: '#34D399',
    domains: ['mobile', 'malware'],
    cfg: [
      { key: 'Input formats', value: 'jadx app.apk / app.dex / app.jar / app.aab', note: 'Also accepts .zip containing DEX files; AAB requires extra args for splits' },
      { key: 'GUI launch', value: 'jadx-gui app.apk', note: 'Search (Ctrl+F / Ctrl+Shift+F), navigation, deobfuscation toggle in menu' },
      { key: 'Deobfuscation', value: 'jadx --deobf app.apk\nor Preferences > Deobfuscation in GUI', note: 'Renames classes/methods from a/b/c to class_1/method_2; improves readability' },
      { key: 'Output dir', value: 'jadx -d out/ app.apk', note: 'Generates out/sources/ (Java) and out/resources/ (XML, assets, raw)' },
      { key: 'Threads', value: 'jadx --threads-count 8 app.apk', note: 'Parallelise decompilation of large apps; default is CPU count' },
      { key: 'Export Gradle', value: 'jadx --export-gradle app.apk', note: 'Generates build.gradle so output compiles directly in Android Studio' },
      { key: 'Show bad code', value: 'jadx --show-bad-code app.apk', note: 'Includes fallback bytecode for methods JADX could not decompile' },
      { key: 'Plugins', value: '~/.jadx/plugins/ — drop plugin JARs', note: 'jadx-gui-plugins: frida-export, ida-export, custom transformers' },
    ],
    hk: [
      { keys: ['Ctrl', 'F'], action: 'Find in current file', context: 'GUI' },
      { keys: ['Ctrl', 'Shift', 'F'], action: 'Search across all classes', context: 'GUI' },
      { keys: ['Ctrl', 'G'], action: 'Go to line', context: 'GUI' },
      { keys: ['Alt', '←'], action: 'Navigate back', context: 'GUI' },
      { keys: ['Ctrl', 'Click'], action: 'Go to declaration', context: 'GUI' },
      { keys: ['X', '/Right-click'], action: 'Find usages of symbol', context: 'GUI' },
      { keys: ['F5'], action: 'Reload / re-decompile', context: 'GUI' },
      { keys: ['Ctrl', 'S'], action: 'Save all decompiled sources', context: 'GUI' },
      { keys: ['Ctrl', 'E'], action: 'Jump to recent files', context: 'GUI' },
    ],
    ho: [
      { direction: 'to', tool: 'Frida', procedure: 'JADX reveals class/method hierarchy → Frida: Java.use("com.pkg.ClassName").targetMethod.implementation = function(arg) { ... }', artifact: 'fully-qualified class + method names' },
      { direction: 'to', tool: 'Ghidra', procedure: 'Shared libraries (.so) inside APK → extract from jadx output/resources/lib/arm64-v8a/ → drag into Ghidra for native layer analysis.', artifact: 'extracted native .so files' },
      { direction: 'to', tool: 'Wireshark', procedure: 'Identify networking class (OkHttp, Retrofit) and endpoint URLs in JADX → confirm traffic in Wireshark with display filter on IP/domain.', artifact: 'endpoint URLs and API patterns' },
      { direction: 'from', tool: 'apktool', procedure: 'apktool d app.apk → smali source; JADX provides more readable Java. Use both: smali for precise byte-level patching, JADX for logic analysis.', artifact: 'smali + Java cross-reference' },
    ],
    pr: [
      { format: '.apk', name: 'Android Package', notes: 'ZIP containing classes.dex, resources.arsc, AndroidManifest.xml, native libs in lib/' },
      { format: '.aab', name: 'Android App Bundle', notes: 'Google Play format; use bundletool to extract base APK before JADX analysis' },
      { format: '.dex', name: 'Dalvik Executable', notes: 'Compiled bytecode for Dalvik/ART VM; multiple dex files possible (multidex)' },
      { format: 'smali', name: 'Smali bytecode', notes: 'Human-readable DEX assembly; use apktool for smali-level patching, JADX for reading' },
      { format: 'AndroidManifest.xml', name: 'App manifest', notes: 'Permissions, activities, services, receivers, providers; critical for attack surface mapping' },
    ],
  },
  {
    id: 'binwalk',
    name: 'Binwalk',
    sub: 'Firmware extraction & analysis',
    color: '#FB923C',
    domains: ['firmware', 'iot'],
    cfg: [
      { key: 'Install', value: 'pip install binwalk\napt install binwalk (Kali/Ubuntu)', note: 'Also installs jefferson, ubi_reader, sasquatch for full filesystem support' },
      { key: 'Extraction', value: 'binwalk -e firmware.bin\nbinwalk --extract firmware.bin', note: 'Outputs to _firmware.bin.extracted/; use -M for recursive extraction of nested archives' },
      { key: 'Signature scan', value: 'binwalk firmware.bin', note: 'Identifies: kernel, rootfs, bootloader, certificates, compression headers, file systems' },
      { key: 'Entropy analysis', value: 'binwalk -E firmware.bin\nbinwalk --entropy firmware.bin', note: 'High entropy (>0.9) = compressed/encrypted; flat entropy = raw code or padding' },
      { key: 'Squashfs / JFFS2', value: 'unsquashfs filesystem.squashfs\njefferson jffs2.img', note: 'binwalk -e handles both automatically; mount -t squashfs for live inspection' },
      { key: 'Custom signatures', value: '~/.config/binwalk/magic — add custom magic bytes', note: 'Format: offset bytes description; reuse libmagic syntax' },
      { key: 'Carve specific type', value: 'binwalk --dd "jpeg image:jpg" firmware.bin', note: 'Carve only matching files; useful for extracting certs, keys, images' },
      { key: 'Diff two firmware', value: 'bindiff fw_v1.bin fw_v2.bin', note: 'Shows added/removed/changed bytes; pair with r2 for changed function analysis' },
    ],
    hk: [
      { keys: ['-e'], action: 'Extract files from firmware', context: 'CLI' },
      { keys: ['-M'], action: 'Recursive extraction (matryoshka mode)', context: 'CLI' },
      { keys: ['-E'], action: 'Entropy plot (identify encryption/compression)', context: 'CLI' },
      { keys: ['-A'], action: 'Scan for CPU opcodes (architecture detection)', context: 'CLI' },
      { keys: ['-C'], action: 'Scan for certificate / key files', context: 'CLI' },
      { keys: ['-l', 'N'], action: 'Limit output to first N results', context: 'CLI' },
      { keys: ['-o', 'N'], action: 'Skip first N bytes before scanning', context: 'CLI' },
      { keys: ['--log', 'out.csv'], action: 'Write results to CSV log file', context: 'CLI' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'binwalk -e firmware.bin → locate kernel image or main application binary in extracted dir → drag into Ghidra with correct arch/endianness.', artifact: 'extracted ELF / raw binary' },
      { direction: 'to', tool: 'Radare2', procedure: 'binwalk -e fw.bin → r2 -a mips -e cfg.bigendian=true _fw.bin.extracted/squashfs-root/usr/bin/app', artifact: 'extracted binary with known arch' },
      { direction: 'to', tool: 'Wireshark', procedure: 'Extract /etc/ssl/certs/ or embedded private keys from firmware → load key in Wireshark TLS decryption to decrypt device traffic.', artifact: 'embedded TLS private key / certs' },
      { direction: 'from', tool: 'Serial Port Monitor', procedure: 'UART console reveals boot log → identifies filesystem type (JFFS2, SquashFS, UBI) → confirms extraction target for binwalk.', artifact: 'boot log with FS hints' },
    ],
    pr: [
      { format: 'SquashFS', name: 'SquashFS', notes: 'Read-only compressed rootfs; magic 0x73717368; mount with loopback or unsquashfs' },
      { format: 'JFFS2', name: 'JFFS2 / UBIFS', notes: 'Flash-friendly journaling FS; jefferson for JFFS2; ubireader for UBI/UBIFS volumes' },
      { format: 'LZMA / gzip', name: 'Compressed kernel', notes: 'uImage header (0x27051956) + compression; binwalk auto-detects and extracts' },
      { format: 'UBI', name: 'UBI volume image', notes: 'Used on NAND flash; ubireader_extract_images for volume extraction' },
      { format: 'TRX', name: 'TRX / CFE header', notes: 'Broadcom router firmware container; magic 0x30524448; contains kernel + rootfs partitions' },
    ],
  },
  {
    id: 'gdb',
    name: 'GDB + pwndbg',
    sub: 'Linux / embedded debugger',
    color: '#F43F5E',
    domains: ['malware', 'iot', 'firmware'],
    cfg: [
      { key: 'pwndbg install', value: 'git clone https://github.com/pwndbg/pwndbg\ncd pwndbg && ./setup.sh', note: 'Replaces peda/gef; adds heap inspection, ROP gadgets, context display' },
      { key: 'GDB init file', value: '~/.gdbinit — source /path/to/pwndbg/gdbinit.py', note: 'Also set: set disassembly-flavor intel, set follow-fork-mode child' },
      { key: 'Remote stub', value: 'gdbserver :1234 ./target\ngdb> target remote host:1234', note: 'For embedded targets: OpenOCD (JTAG), QEMU -s -S, or kernel stub via /proc/kcore' },
      { key: 'QEMU user-mode', value: 'qemu-arm-static -g 1234 ./arm_binary\ngdb-multiarch> target remote :1234', note: 'Cross-arch debugging on x86 host; install gdb-multiarch and qemu-user-static' },
      { key: 'Attach to process', value: 'gdb -p PID\nor gdb> attach PID', note: 'Requires ptrace permissions; set /proc/sys/kernel/yama/ptrace_scope = 0 if blocked' },
      { key: 'Core dumps', value: 'ulimit -c unlimited; ./target\ngdb ./target core', note: 'Inspect crash state post-mortem; coredumpctl for systemd-captured dumps' },
      { key: 'Python scripting', value: 'gdb.execute() / gdb.parse_and_eval()', note: 'Full Python 3 API inside GDB; write custom commands with gdb.Command subclass' },
      { key: 'TUI mode', value: 'gdb -tui or Ctrl+X A inside GDB', note: 'Split source/disasm/registers panes; layout src/asm/regs/split commands' },
    ],
    hk: [
      { keys: ['b', '*0x401000'], action: 'Set breakpoint at address', context: 'GDB' },
      { keys: ['r', '[args]'], action: 'Run / restart target', context: 'GDB' },
      { keys: ['c'], action: 'Continue execution', context: 'GDB' },
      { keys: ['ni'], action: 'Step over (next instruction)', context: 'GDB' },
      { keys: ['si'], action: 'Step into (single instruction)', context: 'GDB' },
      { keys: ['fin'], action: 'Run until function return', context: 'GDB' },
      { keys: ['x/20wx', '$sp'], action: 'Examine stack (20 words, hex)', context: 'GDB' },
      { keys: ['info', 'registers'], action: 'Show all registers', context: 'GDB' },
      { keys: ['disas', 'func'], action: 'Disassemble function', context: 'GDB' },
      { keys: ['bt'], action: 'Backtrace (call stack)', context: 'GDB' },
      { keys: ['watch', '*addr'], action: 'Hardware watchpoint on memory address', context: 'GDB' },
      { keys: ['set', '{int}0xaddr=0x90'], action: 'Patch byte at address (NOP)', context: 'GDB' },
      { keys: ['ctx'], action: 'pwndbg: full context (regs, stack, disasm)', context: 'pwndbg' },
      { keys: ['heap'], action: 'pwndbg: inspect heap chunks', context: 'pwndbg' },
    ],
    ho: [
      { direction: 'to', tool: 'Ghidra', procedure: 'GDB log runtime addresses → match to Ghidra static addresses via base address delta. Script: python3 -c "print(hex(gdb_addr - base + ghidra_base))"', artifact: 'runtime→static address mapping' },
      { direction: 'from', tool: 'Radare2', procedure: 'r2 analysis identifies function names and offsets → set GDB breakpoints by name: b *base+offset or use gdbserver with r2 debug backend (r2 -d gdb://host:1234).', artifact: 'function offsets from r2' },
      { direction: 'from', tool: 'Binwalk', procedure: 'Firmware extracted and QEMU-emulated → GDB remote stub via QEMU -s -S; cross-debug extracted binaries without physical hardware.', artifact: 'QEMU-emulated firmware process' },
      { direction: 'to', tool: 'Frida', procedure: 'GDB for native Linux; Frida for Android/iOS. On Linux targets, prefer GDB for kernel/boot; use Frida for userspace API hooking without restarting process.', artifact: 'complementary coverage boundary' },
    ],
    pr: [
      { format: '.gdb', name: 'GDB script', notes: 'Sequence of GDB commands; run with gdb -x script.gdb ./binary or source inside session' },
      { format: 'core', name: 'Core dump', notes: 'ELF snapshot of crashed process memory + registers; load with gdb ./binary core' },
      { format: 'GDB/MI', name: 'GDB Machine Interface', notes: 'Structured output protocol used by IDEs (VS Code, CLion); gdb --interpreter=mi' },
      { format: 'RSP', name: 'GDB Remote Serial Protocol', notes: 'Text protocol over TCP/serial; implemented by gdbserver, OpenOCD, QEMU, J-Link' },
    ],
  },
];

export const RE_TOOLS_MAP: Record<ToolId, RETool> = Object.fromEntries(
  RE_TOOLS.map(t => [t.id, t])
) as Record<ToolId, RETool>;
